package bsuir.epam.first_application.constants;

public final class Constants {
    private Constants() {}
    public static final byte SET_V_GAP = 5;
    public static final byte SET_H_GAP = 5;
    public static final byte INSETS_TOP = 10;
    public static final byte INSETS_RIGHT = 10;
    public static final byte INSETS_BOTTOM = 10;
    public static final byte INSETS_LEFT = 10;
    public static final byte TEXT_1_COR_X = 0;
    public static final byte TEXT_1_COR_Y = 0;
    public static final byte TEXT_2_COR_X = 0;
    public static final byte TEXT_2_COR_Y = 1;
    public static final byte TEXT_3_COR_X = 0;
    public static final byte TEXT_3_COR_Y = 2;
    public static final byte UNDER_TEXT_1_COR_X = 0;
    public static final byte UNDER_TEXT_1_COR_Y = 3;
    public static final byte UNDER_TEXT_2_COR_X = 0;
    public static final byte UNDER_TEXT_2_COR_Y = 4;
    public static final byte UNDER_TEXT_3_COR_X = 0;
    public static final byte UNDER_TEXT_3_COR_Y = 5;
    public static final byte TEXT_FIELD_1_COR_X = 1;
    public static final byte TEXT_FIELD_1_COR_Y = 0;
    public static final byte TEXT_FIELD_2_COR_X = 1;
    public static final byte TEXT_FIELD_2_COR_Y = 1;
    public static final byte TEXT_FIELD_3_COR_X = 1;
    public static final byte TEXT_FIELD_3_COR_Y = 2;
    public static final byte MAIN_BUTTON_X = 2;
    public static final byte MAIN_BUTTON_Y = 5;
    public static final byte CLEAR_BUTTON_X = 2;
    public static final byte CLEAR_BUTTON_Y = 4;
    public static final byte ABOVE_TEXT__1_COR_X = 1;
    public static final byte ABOVE_TEXT__1_COR_Y = 3;
    public static final byte ABOVE_TEXT__2_COR_X = 1;
    public static final byte ABOVE_TEXT__2_COR_Y = 4;
    public static final byte ABOVE_TEXT__3_COR_X = 1;
    public static final byte ABOVE_TEXT__3_COR_Y = 5;
    public static final String YEP = "Yep";
    public static final String NOPE = "Nope";
    public static final String IF_ERROR = "Wrong input is HERE!";
    public static final String NOTHING = "";
    public static final String MAIN_BUTTON_TEXT = "Check it";
    public static final String CLEAR_BUTTON_TEXT = "Clear fields";
    public static final String TEXT_1_STRING = "Side 1";
    public static final String TEXT_2_STRING = "Side 2";
    public static final String TEXT_3_STRING = "Side 3";
    public static final String UNDER_TEXT_1_STRING = "Equilateral triangle: ";
    public static final String UNDER_TEXT_2_STRING = "Isosceles triangle: ";
    public static final String UNDER_TEXT_3_STRING = "Right triangle: ";
}
